"""Build an offline annotation form from the already-collected whole posts."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = json.loads((root / "collection/sources.json").read_text())["posts"]
payload = json.dumps(data, ensure_ascii=False).replace("<", "\\u003c")
html = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TakeMeter — student annotation</title>
<style>
body{margin:0;background:#f3f5fa;color:#162138;font:16px/1.55 system-ui,sans-serif}main{max-width:940px;margin:auto;padding:28px}h1{margin-bottom:4px}section{background:white;border:1px solid #dce1eb;border-radius:14px;padding:24px;margin:20px 0}h2{margin-top:0}button,input,select,textarea{font:inherit}button{background:#164f95;color:white;border:0;border-radius:8px;padding:11px 16px;margin:5px 5px 5px 0;cursor:pointer}button.secondary{background:#e8edf5;color:#162138}button:disabled{opacity:.4;cursor:default}textarea,input,select{box-sizing:border-box;padding:10px;border:1px solid #b6c0d0;border-radius:7px;width:100%;margin:6px 0}textarea{min-height:86px}.post{white-space:pre-wrap;background:#f8fafc;padding:18px;border-radius:8px;overflow-wrap:anywhere}small,.muted{color:#546277}.badge{display:inline-block;background:#eef3fc;padding:4px 10px;border-radius:30px}.criterion{border-top:1px solid #ddd;padding-top:12px;margin-top:12px}#message{font-weight:600;color:#175c38}a{color:#164f95}.row{display:flex;gap:12px;flex-wrap:wrap}.row>*{flex:1;min-width:190px}details{margin:12px 0}progress{width:100%;height:16px}
</style><main>
<h1>TakeMeter</h1><p class="muted">Hacker News AI discussions · student annotation and criteria</p>
<section><h2>Before you label</h2><p>Read the 40-post reading pack and proposed taxonomy in the project ZIP. These are AI-assisted draft definitions. Decide whether they measure the distinction you want.</p><p>The first 20 posts have <strong>no AI labels or suggestions</strong>. Label them yourself before requesting any pre-labeling. All later posts in this form are also unlabeled; you may complete them manually or return after the cold batch for AI assistance.</p>
<details open><summary>Proposed definitions</summary><ul><li><strong>analysis:</strong> Supports its main claim with a specific, checkable detail, a concrete first-hand observation, or a cited source.</li><li><strong>unsupported:</strong> Primarily a statement, judgment, joke, agreement, or reaction without specific support for its main point.</li><li><strong>question:</strong> Primarily requests information or clarification without advancing its own answer or advocating a conclusion.</li></ul><p>Specific support must relate to the main claim. "I agree 100%" is not evidence. A rhetorical or self-answered question follows the statement rule. Classifying support does not fact-check it.</p></details>
<p><label><input id="taxonomy_ok" type="checkbox" style="width:auto"> I reviewed these definitions and will apply them consistently. If I need different definitions, I will revise the project before labeling.</label></p>
</section>
<section><h2>Your five acceptance criteria</h2><p>Write each criterion and its numeric target yourself. Explain why you chose that target. Cover at least three of the areas below. No targets or finished criteria are supplied here. Commit the exported criteria before training.</p><div id="criteria"></div><button id="criteria_export">Download criteria.md</button><small>Choose the evaluation set and calculation clearly. In Unit 6, targets must hold across all three seeds when applicable.</small></section>
<section><h2>Label complete posts</h2><div id="progress_text"></div><progress id="progress" max="260" value="0"></progress><p><span class="badge" id="stage"></span></p><small id="source"></small><p id="story"></p><div class="post" id="post"></div>
<label>Label<select id="label"><option value="">Choose your label</option><option>analysis</option><option>unsupported</option><option>question</option></select></label>
<label><input id="hard" type="checkbox" style="width:auto"> This is a hard case</label>
<textarea id="note" placeholder="For a hard case: name both candidate labels and explain your choice using the rule."></textarea>
<button id="save">Save label and continue</button><button class="secondary" id="back">Previous</button><button class="secondary" id="next">Next saved post</button>
<p id="counts"></p><button id="csv_export">Download labels.csv</button><button id="state_export">Download review checkpoint</button><label>Resume from a saved checkpoint<input id="state_import" type="file" accept=".json"></label><p class="muted">You can return just the 20 cold labels first. A complete training dataset still requires at least 200 reviewed labels and no class above 70%.</p>
</section><p id="message" role="status"></p><p class="muted">This form runs offline. It sends nothing to a server. Download a checkpoint to preserve your work before closing it. Browser storage may vary when opening a local file.</p></main>
<script>
const posts=__DATA__;
const blankCriteria=()=>Array.from({length:5},()=>({area:'',statement:'',reason:''}));
const KEY='takemeter-hn-review-v1';let state={index:0,taxonomy_ok:false,criteria:blankCriteria(),labels:posts.map(()=>({label:'',note:'',hard:false,saved_at:null}))};
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&saved.labels.length===posts.length)state=saved;}catch(e){}
const $=id=>document.getElementById(id);const message=t=>$('message').textContent=t;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){message('Download a checkpoint to preserve this session.');}}
function download(name,body,type){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([body],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderCriteria(){const container=$('criteria');container.replaceChildren();state.criteria.forEach((c,i)=>{const d=document.createElement('div');d.className='criterion';const h=document.createElement('h3');h.textContent=`Criterion ${i+1}`;d.append(h);const select=document.createElement('select');['','Overall accuracy','Per-label performance','Balance','Consistency','Confidence','Other'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v||'Choose an area';select.append(o)});select.value=c.area;select.onchange=()=>{c.area=select.value;persist()};d.append(select);[['statement','Your criterion, including your numeric target'],['reason','Why you chose this target for this taxonomy or data']].forEach(([key,p])=>{const t=document.createElement('textarea');t.placeholder=p;t.value=c[key];t.setAttribute('aria-label',`Criterion ${i+1}: ${p}`);t.oninput=()=>{c[key]=t.value;persist()};d.append(t)});container.append(d)});}
function render(){const i=state.index,p=posts[i],r=state.labels[i];const done=state.labels.filter(x=>x.label).length;const cold=state.labels.slice(0,20).filter(x=>x.label).length;$('progress_text').textContent=`${done}/${posts.length} labeled · ${cold}/20 cold labels · post ${i+1}`;$('progress').value=done;$('stage').textContent=i<20?'Cold label: your unaided choice':'Manual label: read the whole post';$('source').textContent=`HN ${p.id} · ${p.source_url}`;$('story').textContent=p.story_title;$('post').textContent=p.text;$('label').value=r.label;$('note').value=r.note;$('hard').checked=r.hard;$('taxonomy_ok').checked=state.taxonomy_ok;$('back').disabled=i===0;$('next').disabled=i===posts.length-1||!r.label;const counts={analysis:0,unsupported:0,question:0};state.labels.forEach(x=>{if(x.label in counts)counts[x.label]++});$('counts').textContent=Object.entries(counts).map(([l,n])=>`${l}: ${n} (${done?(100*n/done).toFixed(1):0}%)`).join(' · ');persist();}
$('taxonomy_ok').onchange=()=>{state.taxonomy_ok=$('taxonomy_ok').checked;persist()};
$('save').onclick=()=>{if(!state.taxonomy_ok)return message('Review the taxonomy first.');if(!$('label').value)return message('Choose a label.');if($('hard').checked&&!$('note').value.trim())return message('Explain the two candidate labels and your decision.');state.labels[state.index]={label:$('label').value,note:$('note').value.trim(),hard:$('hard').checked,saved_at:new Date().toISOString()};const missing=state.labels.findIndex(x=>!x.label);if(missing>=0)state.index=missing;message('Label saved.');render()};
$('back').onclick=()=>{state.index=Math.max(0,state.index-1);render()};$('next').onclick=()=>{state.index=Math.min(posts.length-1,state.index+1);render()};
$('criteria_export').onclick=()=>{if(state.criteria.some(c=>!c.area||!c.statement.trim()||!/[0-9]/.test(c.statement)||!c.reason.trim()))return message('Write all five criteria, each with a number, an area and a reason.');if(new Set(state.criteria.filter(c=>c.area!=='Other').map(c=>c.area)).size<3)return message('Cover at least three listed areas.');const text='# Acceptance criteria — TakeMeter\n\nStudent-authored targets, written before training.\n\n'+state.criteria.map((c,i)=>`## ${i+1}. ${c.area}\n\n${c.statement}\n\n**Why this target:** ${c.reason}\n`).join('\n');download('criteria.md',text,'text/markdown');message('Criteria exported. Commit this file before training.');};
const quote=x=>'"'+String(x).replaceAll('"','""')+'"';
$('csv_export').onclick=()=>{const body='text,label,note\r\n'+posts.map((p,i)=>{const r=state.labels[i];const stage=r.label?(i<20?'cold':'manual; human_reviewed'):(i<20?'cold_pending':'unlabeled');const note=`${stage}; hn_id=${p.id}; source=${p.source_url}`+(r.hard?'; hard_case':'')+(r.note?`; ${r.note}`:'');return [p.text,r.label,note].map(quote).join(',')}).join('\r\n')+'\r\n';download('labels.csv',body,'text/csv;charset=utf-8');message('CSV exported. Blank rows remain unfinished, and pending rows are not claimed as cold.');};
$('state_export').onclick=()=>download('review-checkpoint.json',JSON.stringify({version:1,post_ids:posts.map(p=>p.id),state},null,2),'application/json');
$('state_import').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.version!==1||JSON.stringify(d.post_ids)!==JSON.stringify(posts.map(p=>p.id))||d.state.labels.length!==posts.length)throw Error('This checkpoint belongs to another collection.');if(d.state.labels.some(r=>r.label&&!['analysis','unsupported','question'].includes(r.label)))throw Error('Unknown label.');state=d.state;renderCriteria();render();message('Checkpoint restored.');}catch(err){message(err.message);}};
renderCriteria();render();
</script></html>'''
(root / "annotation_review.html").write_text(html.replace("__DATA__", payload), encoding="utf-8")
print("Built offline review form with all 260 complete posts and no suggested labels.")
